const type = {
    ADMIN_LOGIN: 'ADMIN_LOGIN',
    FETCH_VIDEO_PER_PAGE: 'FETCH_VIDEO_PER_PAGE',
    FETCH_ALL_USERS: 'FETCH_ALL_USERS',
    SEE_ALL_VIDEOS: 'SEE_ALL_VIDEOS',

    //  add Video page
    ADD_VIDEO: 'ADD_VIDEO',
    UPLOAD_VIDEO: 'UPLOAD_VIDEO',
    UPLOAD_CSV: 'UPLOAD_CSV',
    CANCEL_CSV: 'CANCEL_CSV',
    TOGGLE_CSV: 'TOGGLE_CSV',
    DISMISS_MODAL: 'DISMISS_MODAL',
    OPEN_MODAL: 'OPEN_MODAL',
    NEW_CATEGORY: 'NEW_CATEGORY',
    NEW_REGION: 'NEW_REGION',
    ADD_CATEGORY: 'ADD_CATEGORY',
    ADD_REGION: 'ADD_REGION',
    END_ADD_VIDEO: 'END_ADD_VIDEO',

    // video list page
    FETCH_ALL_VIDEOS: 'FETCH_ALL_VIDEOS',
    FETCH_ALL_CATEGORY: 'FETCH_ALL_CATEGORY',
    FETCH_ALL_REGION: 'FETCH_ALL_REGION',
    STATUS_YES: 'STATUS_YES',
    STATUS_NO: 'STATUS_NO',
    DELETE_ROW: 'DELETE_ROW',
    OPEN_EDIT_ROW: 'OPEN_EDIT_ROW',
    SELECT_CHANGE: 'SELECT_CHANGE',
    UPDATE_VIDEO_DETAILS: 'UPDATE_VIDEO_DETAILS',
    // logout
}

export default type;